// src/components/FontSelect.svelte
<script lang="ts">
  import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
  } from "@/components/ui/select";
  import { onMount } from "svelte";

  const fontList = [
    {
      name: "芫荽體",
      value: "iansui",
      className: "font-iansui",
    },
    {
      name: "粉圓體",
      value: "huninn",
      className: "font-huninn",
    },
  ];

  let selectedFont = $state("iansui");

  onMount(() => {
    if (typeof window === "undefined") return;

    const localFont = localStorage.getItem("font");
    if (localFont) {
      selectedFont = localFont;
    }
  });

  function handleChange(value: string) {
    selectedFont = value;
    localStorage.setItem("font", value);

    if (typeof window !== "undefined") {
      window.toggleFont(value);
    }
  }

  const font = $derived(fontList.find((font) => font.value === selectedFont));
</script>

<Select type="single" value={selectedFont} onValueChange={handleChange}>
  <SelectTrigger class={font?.className}>
    <span data-slot="select-value">
      {font?.name}
    </span>
  </SelectTrigger>
  <SelectContent>
    {#each fontList as font (font.value)}
      <SelectItem value={font.value} class={font.className}>
        {font.name}
      </SelectItem>
    {/each}
  </SelectContent>
</Select>

// src/components/FontSelect.tsx
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import React from "react";

const fontList = [
  {
    name: "芫荽體",
    value: "iansui",
    className: "font-iansui",
  },
  {
    name: "粉圓體",
    value: "huninn",
    className: "font-huninn",
  },
];

const FontSelect = () => {
  const [selectedFont, setSelectedFont] = React.useState("iansui");

  React.useEffect(() => {
    if (typeof window === "undefined") return;

    const localFont = localStorage.getItem("font");
    if (localFont) {
      setSelectedFont(localFont);
    }
  }, []);

  const handleChange = (value: string) => {
    setSelectedFont(value);

    localStorage.setItem("font", value);

    window.toggleFont(value);
  };

  const fontClassName = fontList.find(
    (font) => font.value === selectedFont,
  )?.className;

  return (
    <Select value={selectedFont} onValueChange={handleChange}>
      <SelectTrigger className={fontClassName}>
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {fontList.map((font) => (
          <SelectItem
            key={font.value}
            value={font.value}
            className={font.className}
          >
            {font.name}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
};

export default FontSelect;
