// src/components/md/Button.tsx
import {
  Button as ButtonUI,
  type buttonVariants,
} from "@/components/ui/button";
import type { VariantProps } from "class-variance-authority";

const Button = ({
  href,
  children,
  style,
  rel,
}: {
  href: string;
  variant?: VariantProps<typeof buttonVariants>["variant"];
  children: React.ReactNode;
  style?: string;
  rel?: string;
}) => {
  return (
    <ButtonUI className="no-underline" asChild>
      <a
        href={href}
        target="_blank"
        rel={`noopener noreferrer ${
          rel ? (rel === "follow" ? "" : rel) : "nofollow"
        }`}
      >
        {children}
      </a>
    </ButtonUI>
  );
};

export default Button;

// src/components/md/Button.svelte
<script lang="ts">
  import type { buttonVariants } from "@/components/ui/button";
  import { Button as ButtonUI } from "@/components/ui/button";
  import type { VariantProps } from "class-variance-authority";
  import type { Snippet } from "svelte";

  interface Props {
    href: string;
    variant?: VariantProps<typeof buttonVariants>["variant"];
    children: Snippet;
    rel?: string;
  }

  let { href, variant, children, rel }: Props = $props();
</script>

<ButtonUI
  class="no-underline"
  {variant}
  {href}
  target="_blank"
  rel="noopener noreferrer {rel ? (rel === 'follow' ? '' : rel) : 'nofollow'}"
>
  {@render children()}
</ButtonUI>
